// Generated by CoffeeScript 1.6.3
/*
 # Module dependencies.
*/


(function() {
  var app, express, http, io, mongoURI, mongoose, path, routes, server, socketio;

  console.log("fire app.js");

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  mongoose = require('mongoose');

  socketio = require('socket.io');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, '/../public')));

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  server = http.createServer(app);

  io = socketio.listen(server);

  mongoURI = process.env.MONGOHQ_URL || 'mongodb://localhost/rankedvoting';

  mongoose.connect(mongoURI);

  app.get('/', routes.index);

  app.post('/submitdata', function(req, res) {
    var submitedInfo;
    submitedInfo = req.body;
    console.log("submitedInfo", submitedInfo);
  });

  app.get('/chocolate', routes.chocolate);

  app.get('/tabulate', routes.tabulate);

  server.listen(app.get('port'), function() {
    console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
